[
  "python >=3.5.3"
  "llvmlite-artiq"
  "binutils-or1k-linux >=2.27"
  "pythonparser >=1.1"
  "scipy"
  "numpy"
  "prettytable"
  "h5py"
  "python-dateutil"
  "pyqt >=5.5"
  "quamash"
  "pyqtgraph 0.10.0"
  "pygit2"
  "python-levenshtein"
  "sipyco"
]
